#!/usr/bin/env python3

# PREPROCESSOR FOR TSS8 OR OS8 PAL8 FILE

LIMIT = 55

import sys

def minify(text):
    text = text.strip().replace('\t', ' ').upper()
    temp = ',' + text.replace(' ', '')
    if ',TEXT' in temp:
        delim = temp.partition(',TEXT')[2][0]
        text = text.split(delim, 1)[0].replace(' ', '') + ' ' + delim + text.split(delim)[1] + delim
    else:
        while '  ' in text:
            text = text.replace('  ', ' ')
        while '; ' in text:
            text = text.replace('; ', ';')
        while ', ' in text:
            text = text.replace(', ', ',')
        text = text.split("/", 1)[0]
    return text.strip()

# read PAL8 file
linelist = sys.stdin.read().split('\n')

# Generate our PAL8 program
lines = ""
for i, line in enumerate(linelist):

    line = minify(line)
    if len(line) > 0:
        # concatenate line
        if len(lines) > LIMIT:
            print(lines)
            lines = line
        else:
            if len(lines) > 0:
                lines += ';' + line
            else:
                lines = line

# Finish up
if len(lines) > 0:
    print(lines)
